
[[app]]
file = 'apps/alarm.py'
auto_load = true

[[app]]
file = 'apps/timer.py'

[[app]]
file = 'apps/game_of_life.py'

[[app]]
file = 'apps/hello.py'

[[app]]
file = 'apps/level.py'

[[app]] # If only one watch face is included this app can be removed
file = 'apps/faces.py'
auto_load = true
no_except = true

[[watchface]]
file = 'watch_faces/clock.py'

[[watchface]]
file = 'watch_faces/word_clock.py'
